version: "3"
services:
  web-tomcat:
    ports:
     - 8081:8080
    build:
      context: ./
      args:
          - GIT_USR=Kir3103
          - GIT_PWD=Rbhbkk96*
    links:
    - db
  
  db:
    image: mysql:5.7
    ports:
     - 3307:3306
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=login
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=union_reporting
